version: '3.1'
services:      
  download-dot-particubes:
    environment:
      - VIRTUAL_HOST=download.particubes.com
    volumes:
      - /home/adrien/download.particubes.content:/content:ro

networks:
  default:
    external:
      name: websites